### PR TITLE
Support MaxMind License Key, SQL Error fix (obsolete, see PR #9)

### PR DESCRIPTION
**Pull request by robertoschwald**
Obsolete. Please see new PR #9 

~~This PR adds the following new features / fixes:~~

1. MaxMind now needs a License Key for GeoLite2 files to be downloaded for legal reasons.
- New setting for the MaxMind license key
- Changed MaxMind download URLs.
- Handling of new MaxMind download archive format
- Does not delete an existing MaxMind db file prior the download, so the old db stays active until a new db was downloaded and extracted successfully. 
- Always shows last modified if mmdb file exists
- States how often the db gets updated
- Does not use gzopen / gzopen64 anymore, but uses PharData. Extract only the mmdb file from the archive.

2. Fix SQL Error when Events Manager is installed and ‘Posts and Pages’ is enabled
- See https://wordpress.org/support/topic/you-have-an-error-in-your-sql-syntax-22/

3. Increased required PHP to 5.5 (since 4.8.8.1)
- See https://wordpress.org/support/topic/slimstats-4-8-8-1-fails-on-php-5-3-26-but-no-warning-during-installation/

4. Explicitely save options to store new browscap_last_modified to avoid stalled websites when GH is down (as on 2020-04-02, sigh). See #7 

Tested here with these Environments:

- WordPress 5.3.2 (PHP 7.3.12 and 7.3.16)
- WordPress 5.4 (PHP 7.3.16)

### CODE REVIEW

**Comment by robertoschwald** [comment]
Note for all who need GeoLite2 support immediately, even if this PR is not merged:

All steps here are done on your own risk!

You must manually overwrite some files changed in this PR on your server installation.

1. Backup your plugins/wp-slimstat dir of your server, first (be warned!) 

2. Download https://raw.githubusercontent.com/robertoschwald/wp-slimstat/pr_maxmind_license_key_support/admin/config/index.php
3. Upload the file to wp-content/plugins/wp-slimstat/admin/config/index.php 

4. Download https://raw.githubusercontent.com/robertoschwald/wp-slimstat/pr_maxmind_license_key_support/vendor/maxmind.php
5. Upload the file to wp-content/plugins/wp-slimstat/vendor/maxmind.php

6. Download https://raw.githubusercontent.com/robertoschwald/wp-slimstat/pr_maxmind_license_key_support/wp-slimstat.php
7. Upload the file to wp-content/plugins/wp-slimstat/wp-slimstat.php

8. Signup a new account on https://dev.maxmind.com/geoip/geoip2/geolite2/
9. After account activation, create a license key for the latest GeoLite DB. Note the key as you will see it only once! Now wait for 5 minutes, as it takes a while until the license key is activated on the MaxMind website.
10. In your admin panel, go to wp-slimstat > Settings > Maintenance and enter the GeoLite license key
11. Disable and re-enable MaxMind. The plugin will immediately try to download the database archive and extract the MaxMind database. If it states that the database was successfully installed, you are ready to geolocate your vistors again.

Note: 
As the plugin version stays the same, you must monitor this Pull-Request. If the plugin maintainer releases a new version of the plugin without merging this pull request, you must either leave a comment here, so I can backport the PR into the new plugin version, or you overwrite the files again (dangerous).

**Comment by robertoschwald** [comment]
For the upgrade, it seems to work this way

md5sum the mmdb file (e.g. GeoLite2-City.mmdb)
Access the update URL providing basic-auth credentials (AccountID/LicenseKey) and the param "db_md5=xxxx"

Examples:
https://updates.maxmind.com/geoip/databases/GeoLite2-City/update?db_md5=223747d89354684e21b40cae5436a7ed

https://updates.maxmind.com/geoip/databases/GeoLite2-Country/update?db_md5=89c235e40c55ee253832b31923f0c395

**Comment by mundschenk-at** [comment]
I'm not associated with Jason/Slimstat or anything, but I think it would facilitate (eventual) merging if you could rebase your PR to reduce the number of "partial" commits (e.g. merge the "cleanup" commits containing only whitespace changes to a single one).

**Comment by robertoschwald** [comment]
Seems he dissapeared. No reaction, even on Slack.

**Comment by robertoschwald** [comment]
Squashed the commits. See now PR #9

**Pull request closed without merging**
