### PR TITLE
Support MaxMind License Key, SQL Error fix, small others

### PR DESCRIPTION
**Pull request by robertoschwald**
This is the successor of #5 with squashed commits.

This PR adds the following new features / fixes: 

1. MaxMind now needs a License Key for GeoLite2 files to be downloaded for legal reasons.
- New setting for the MaxMind license key
- Changed MaxMind download URLs.
- Handling of new MaxMind download archive format
- Does not delete an existing MaxMind db file prior the download, so the old db stays active until a new db was downloaded and extracted successfully. 
- Always shows last modified if mmdb file exists
- States how often the db gets updated
- Does not use gzopen / gzopen64 anymore, but uses PharData. Extract only the mmdb file from the archive.

2. Fix SQL Error when Events Manager is installed and ‘Posts and Pages’ is enabled
- See https://wordpress.org/support/topic/you-have-an-error-in-your-sql-syntax-22/

3. Increased required PHP to 5.5 (since 4.8.8.1)
- See https://wordpress.org/support/topic/slimstats-4-8-8-1-fails-on-php-5-3-26-but-no-warning-during-installation/

4. Explicitely save options to store new browscap_last_modified to avoid stalled websites when GH is down (as on 2020-04-02, sigh). See #7 

5. Use whatismyipaddress instead of infosniper for whois, as infosniper seems to be gone.

Tested here with these Environments:

- WordPress 5.3.2 (PHP 7.3.12 and 7.3.16)
- WordPress 5.4 (PHP 7.3.17)
- WordPress 5.5 (PHP 7.4.9)
- WordPress 5.5.2 (PHP 7.4.11)
- WordPress 5.6 (PHP 7.4.13)

### CODE REVIEW

**Comment by robertoschwald** [comment]
Note for all who need GeoLite2 support immediately, even if this PR is not merged.
Download the inofficial pre-release from https://github.com/robertoschwald/wp-slimstat/releases/tag/v4.8.8.2-pr9pre1 and install on the WP plugin install page,or perform these steps manually in your installation:

All steps here are done on your own risk!

You must manually overwrite some files changed in this PR on your server installation.

Backup your plugins/wp-slimstat dir of your server, first (be warned!)

Download https://raw.githubusercontent.com/robertoschwald/wp-slimstat/feature/pr_maxmind_and_other_fixes/admin/config/index.php

Upload the file to wp-content/plugins/wp-slimstat/admin/config/index.php

Download https://raw.githubusercontent.com/robertoschwald/wp-slimstat/feature/pr_maxmind_and_other_fixes/vendor/maxmind.php

Upload the file to wp-content/plugins/wp-slimstat/vendor/maxmind.php

Download https://raw.githubusercontent.com/robertoschwald/wp-slimstat/feature/pr_maxmind_and_other_fixes/wp-slimstat.php

Upload the file to wp-content/plugins/wp-slimstat/wp-slimstat.php

Signup a new account on https://dev.maxmind.com/geoip/geoip2/geolite2/

After account activation, create a license key for the latest GeoLite DB. Note the key as you will see it only once! Now wait for 5 minutes, as it takes a while until the license key is activated on the MaxMind website.

In your admin panel, go to wp-slimstat > Settings > Maintenance and enter the GeoLite license key

Disable and re-enable MaxMind. The plugin will immediately try to download the database archive and extract the MaxMind database. If it states that the database was successfully installed, you are ready to geolocate your vistors again.

Note:
As the plugin version stays the same, you must monitor this Pull-Request. If the plugin maintainer releases a new version of the plugin without merging this pull request, you must either leave a comment here, so I can backport the PR into the new plugin version, or you overwrite the files again (dangerous).

**Comment by darrin-rambillo** [comment]
@robertoschwald Thanks for picking this up from the plugin maintainer. Are your PR files mentioned in https://github.com/slimstat/wp-slimstat/pull/9#issuecomment-618973769 still available?  Clicking them gives 404s currently.

**Comment by robertoschwald** [comment]
Good point. Urls are fixed.

**Comment by inspiredearth** [comment]
Thanks for providing this solution. Hopefully the plug-in developer is okay.

The issue I have is that even with the database installed (I'm using the city version, and set the plug-in option for that to city), the location data is not converted from the IP addresses. I've uploaded the DB myself (to the required folder), and also implemented your file changes (and put in my license key). Still no effect.

Is the plugin actually still displaying location data, or has that broken after recent Wordpress updates?

**Comment by robertoschwald** [comment]
It still works. You do not need to install manually. As soon as you enter the license key and submit, the db is downloaded and extracted. The date of download should be displayed in the text.

**Comment by robertoschwald** [comment]
@slimstat Please review this PR. People are waiting for the fixes. Thanks.

**Pull request merged**
