### PR TITLE
Add email filter

### PR DESCRIPTION
**Pull request by sandrodz**
Hi,

CRM integration plugins in the wild rely mostly on the user Email. Since slimdata only stores username, It is difficult to reliably connect CRM data with slimstat data.

I've added Email filter and corresponding column in the database. I think this addition makes plugin more versatile and easy to use with CRM.

If site owner wishes to add email data retroactively (not fresh install), following query can populate new email column with data from wp_users table:

```
UPDATE wp_slim_stats
INNER JOIN wp_users ON wp_slim_stats.username = wp_users.user_login
SET wp_slim_stats.email = wp_users.user_email
```

I didn't want to run this query during upgrade (with php), due to possibility of massive databases out there.

### CODE REVIEW

**Comment by slimstat** [comment]
Hi there! Thank you for submitting this pull request. I like this idea, and the reason behind it is more than valid. Since this mod would increase the database size, I am thinking that it should be implemented as a switch in the settings, so that admins can enable/disable it as needed. I'm quite sure most of our users would not really need it on their blogs with just a few users. Would you be interested in submitting a modified pull request that implements this as a setting?

**Comment by sandrodz** [comment]
Hey, thanks for the reply, yes I would gladly work on this PR.

**Comment by slimstat** [comment]
Terrific, thank you so much!

**Comment by slimstat** [comment]
Hi there, not sure if you're still working on this pull request. We're moving forward and implementing your feature in the next release. 

Take care,
Jason

**Comment by sandrodz** [comment]
@slimstat That's an awesome news. Unfortunatly I didn't have time to finish my PR :(

**Comment by slimstat** [comment]
No worries, I understand!

**Pull request closed without merging**
